backend:
  - backend/**/*

documentation:
  - docs/**/*
  - Makefile
  - README.md

frontend:
  - src/**/*
  - .eslintrc.json
  - next.config.js
  - next-env.d.ts
  - package.json
  - package-lock.json
  - tsconfig.json
