version: "3"

services:
  api:
    build:
      context: ./backend
      dockerfile: build/Dockerfile
    environment:
      - PORT
      - DSN
      - GOOGLE_CREDENTIALS_JSON
      - ALLOW_ORIGINS
    container_name: tomeit-api
    volumes:
      - ./backend:/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db-local
  db-local:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    container_name: tomeit-api-db-dev
    restart: always
    volumes:
      - data-local:/var/lib/mysql
      - ./backend/build/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  db-test:
    image: mysql:8.0.29
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_test
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    container_name: tomeit-api-db-test
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - data-test:/var/lib/mysql
  docs:
    image: swaggerapi/swagger-ui:v4.11.0
    container_name: tomeit-api-docs
    environment:
      API_URL: openapi.yaml
    ports:
      - "8000:8080"
    volumes:
      - ./docs/openapi.yaml:/usr/share/nginx/html/openapi.yaml

volumes:
  data-local:
    driver: local
  data-test:
    driver: local
