name: check-backend

on:
  push:
    paths:
      - backend/**

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1
      - name: Run govet
        run: go vet ./...
        working-directory: ./backend
      - name: Run staticcheck
        run: staticcheck ./...
        working-directory: ./backend
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1
      - name: Run test db containenr
        run: docker-compose up -d db-test
        env:
          PORT: 8000
          DSN: foo
          GOOGLE_CREDENTIALS_JSON: bar
          ALLOW_ORIGINS: baz
          MYSQL_ROOT_PASSWORD: qux
          MYSQL_DATABASE: quux
          MYSQL_USER: corge
          MYSQL_PASSWORD: grault
      - name: Test
        run: go test
        working-directory: ./backend
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.1
      - name: Build
        run: go build ./...
        working-directory: ./backend
