name: Deploy Go application

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: "${{ secrets.GAE_CREDENTIALS_JSON }}"
      - name: Deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          working_directory: ./backend
