name: Integrate Go application

on:
  push:
    paths:
      - backend/**

jobs:
  check-style:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - name: Check style
        run: goimports -l .
        working-directory: ./backend
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8
      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1
      - name: Lint with govet
        run: go vet ./...
        working-directory: ./backend
      - name: Lint with Staticcheck
        run: staticcheck ./...
        working-directory: ./backend
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8
      - name: Run db-test container
        run: docker compose up -d db-test
        env:
          PORT: 8000
          DSN: foo
          GOOGLE_CREDENTIALS_JSON: bar
          ALLOW_ORIGINS: baz
          MYSQL_ROOT_PASSWORD: qux
          MYSQL_DATABASE: quux
          MYSQL_USER: corge
          MYSQL_PASSWORD: grault
      - name: Test
        run: go test ./...
        working-directory: ./backend
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8
      - name: Build
        run: go build ./...
        working-directory: ./backend
