name: Set Labels

on:
  - pull_request

jobs:
  set-labels:
    runs-on: ubuntu-20.04
    steps:
      - name: Set labels
        uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/labeler-config.yml"
          sync-labels: true
